pipeline {
    agent any

    environment {
        REGISTRY = "docker.io"
        IMAGE = "naman1514/fraud-detection"
        DOCKER_HOST_CMD = "docker -H tcp://host.docker.internal:2375"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Naman-1508/Fraud-Detection.git'
            }
        }

        stage('SonarQube Scan') {
            steps {
                withSonarQubeEnv('Sonar') {
                    sh """
                        sonar-scanner \
                          -Dsonar.projectKey=fraud-detection \
                          -Dsonar.sources=./src \
                          -Dsonar.host.url=http://host.docker.internal:9000
                    """
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    ${DOCKER_HOST_CMD} build -t ${IMAGE}:${BUILD_NUMBER} .
                """
            }
        }

        stage('Trivy Security Scan') {
            steps {
                sh """
                    trivy image --exit-code 0 --severity HIGH,CRITICAL ${IMAGE}:${BUILD_NUMBER}
                """
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh """
                        echo "$PASS" | ${DOCKER_HOST_CMD} login -u "$USER" --password-stdin
                    """
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                sh """
                    ${DOCKER_HOST_CMD} push ${IMAGE}:${BUILD_NUMBER}
                """
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                    kubectl apply -f k8s/namespace.yaml
                    kubectl apply -f k8s/deployment.yaml
                    kubectl apply -f k8s/service.yaml
                    kubectl apply -f k8s/hpa.yaml
                    kubectl apply -f k8s/ingress.yaml
                """
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully!"
        }
    }
}